### ISSUE TITLE
Investigate alternative ways to distribute and support code release assets

### ISSUE THREAD

**Issue by pzrq** [UNSWComputing/rUNSWift-2017-release#1]
As noted in email chains [and on Slack](https://runswift.slack.com/archives/C2G9ZL0VA/p1517556939000164), the code release assets, such as `sysroot_legacy.tar.gz` referenced in the [bin/build_setup.sh](https://github.com/UNSWComputing/rUNSWift-2017-release/blob/master/bin/build_setup.sh) script need to be accessible anywhere in the world.

However, at this time http://runswift.cse.unsw.edu.au/ and http://runswift.cse.unsw.edu.au/opennao2/build-2.1.3.3/ does not appear to be serving those files anymore, if one is outside the UNSW CSE firewall. Anecdotally from past experience, this server has been unreliable, needing downtime, maintenance, etc

The goal of this ticket is to investigate alternative ways of distributing the coderelease assets to support remote teams, such as those at competitions.

## Candidates

1. Restore CSE firewall hole rule (not sure how to do this)
2. GitHub: Investigate if a public https://github.com/UNSWComputing/rUNSWift-assets/ repository can be created, and see if coderelease assets can be hosted there more reliably
3. Open to ideas 👍

**Comment by pzrq** [comment]
In the absence of more guidance, I will attempt to get Option 2 above working and upgrade this 2017 code release accordingly, though I am next free to attempt this on Thursday evening AEDT.

**Comment by Roclemir** [comment]
Hi Peter,

I have personally attempted to do a very similar thing with Github. I was
able to create a folder and add it to the .gitignore and upload the files
to that folder. Unfortunatelyl this only works for raw files of less than
25mb, this is a limitation imposed by Github.

If you choose to do this, just remember that you will need to get the link
to the raw file, which isn't quite the same link as if you were to download
the file through a browser; most notably, link to raw files don't include
version control or any other nice features that Github has to offer. There
is more information on this at this StackOverflow questions:
https://stackoverflow.com/questions/4604663/download-single-files-from-github

Hope that helps.

**Comment by timewiley** [comment]
I’m not concerned one way or another with regards to where the files are hosted, provided that we abide by the terms of the license agreements.

RE: runswift server.
I run an apache webserver for the robotics lab quite easily on another VM, and I also run a wordpress website for the CRL on a VM.
Neither require special firewall rules, as far as I am aware.


Regards,
Tim

**Comment by pzrq** [comment]
Relevant assets are published in:
https://github.com/UNSWComputing/rUNSWift-assets/releases/tag/v2017.1

I will update the [`bin/build_setup.sh`](https://github.com/UNSWComputing/rUNSWift-2017-release/blob/master/bin/build_setup.sh) in this repository with an `ASSETS_LOCATION` environment variable (i.e. replace all the `http://runswift.cse.unsw.edu.au/opennao2/build-2.1.3.3/` stuff) when time permits.

PRs from anyone else who needs it more quickly would be welcome 👍
