### ISSUE TITLE
2009 Release

### ISSUE THREAD

**Issue by alex-kozinov** [UNSWComputing/rUNSWift-2017-release#3]
Hello!
I am a member of new RoboCup team and we are looking for your open-loop walking code which you spoken about in this thesis: [TayThesisB](https://www.cse.unsw.edu.au/~robocup/2009site/reports/TayThesisB.pdf). 
Please help us, It's essential issue for us because of coming  qualification:)

**Comment by jayenashar** [comment]
Do you need the 2009 walk?  The 2010 walk was better, and 2014 walk even better.

**Comment by pzrq** [comment]
Hi @alex-kozinov if you have further questions, please feel welcome to ask then against the latest release (currently 2019): https://github.com/UNSWComputing/

I am archiving this repo as it is not in any way supported, thank you!
